
// This file has been generated by the GUI designer. Do not modify.

public partial class ClienteWindow
{
	private global::Gtk.Fixed fixed7;
	private global::Gtk.Entry txt_telefono;
	private global::Gtk.Entry txt_nombre;
	private global::Gtk.Label label12;
	private global::Gtk.Label label13;
	private global::Gtk.Button btn_guardar;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget ClienteWindow
		this.Name = "ClienteWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("ClienteWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child ClienteWindow.Gtk.Container+ContainerChild
		this.fixed7 = new global::Gtk.Fixed ();
		this.fixed7.Name = "fixed7";
		this.fixed7.HasWindow = false;
		// Container child fixed7.Gtk.Fixed+FixedChild
		this.txt_telefono = new global::Gtk.Entry ();
		this.txt_telefono.CanFocus = true;
		this.txt_telefono.Name = "txt_telefono";
		this.txt_telefono.IsEditable = true;
		this.txt_telefono.InvisibleChar = '•';
		this.fixed7.Add (this.txt_telefono);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed7 [this.txt_telefono]));
		w1.X = 24;
		w1.Y = 102;
		// Container child fixed7.Gtk.Fixed+FixedChild
		this.txt_nombre = new global::Gtk.Entry ();
		this.txt_nombre.CanFocus = true;
		this.txt_nombre.Name = "txt_nombre";
		this.txt_nombre.IsEditable = true;
		this.txt_nombre.InvisibleChar = '•';
		this.fixed7.Add (this.txt_nombre);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed7 [this.txt_nombre]));
		w2.X = 26;
		w2.Y = 46;
		// Container child fixed7.Gtk.Fixed+FixedChild
		this.label12 = new global::Gtk.Label ();
		this.label12.Name = "label12";
		this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Nombre</b>");
		this.label12.UseMarkup = true;
		this.fixed7.Add (this.label12);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed7 [this.label12]));
		w3.X = 30;
		w3.Y = 23;
		// Container child fixed7.Gtk.Fixed+FixedChild
		this.label13 = new global::Gtk.Label ();
		this.label13.Name = "label13";
		this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Telefono</b>");
		this.label13.UseMarkup = true;
		this.fixed7.Add (this.label13);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed7 [this.label13]));
		w4.X = 27;
		w4.Y = 79;
		// Container child fixed7.Gtk.Fixed+FixedChild
		this.btn_guardar = new global::Gtk.Button ();
		this.btn_guardar.CanFocus = true;
		this.btn_guardar.Name = "btn_guardar";
		this.btn_guardar.UseUnderline = true;
		this.btn_guardar.Label = global::Mono.Unix.Catalog.GetString ("Guardar");
		this.fixed7.Add (this.btn_guardar);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed7 [this.btn_guardar]));
		w5.X = 57;
		w5.Y = 147;
		this.Add (this.fixed7);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 213;
		this.DefaultHeight = 223;
		this.Show ();
		this.btn_guardar.Clicked += new global::System.EventHandler (this.OnBtnGuardarClicked);
	}
}
